# Generated by Django 5.0.6 on 2024-05-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0003_checkinout'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('Car', 'Car'), ('Motorbike', 'Motorbike'), ('Bicycle', 'Bicycle')], max_length=20)),
                ('fee_per_hour', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
