# Generated by Django 5.0.6 on 2024-05-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0006_checkinout_vehicle_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkinout',
            name='image',
        ),
        migrations.AlterField(
            model_name='checkinout',
            name='plate_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='checkinout',
            name='vehicle_type',
            field=models.CharField(choices=[('Car', 'Car'), ('Motorbike', 'Motorbike'), ('Bicycle', 'Bicycle')], default='Car', max_length=10),
        ),
    ]
