# Generated by Django 5.0.6 on 2024-05-20 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0011_checkin_check_out_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='checked_in',
        ),
        migrations.AlterField(
            model_name='checkin',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
