# Generated by Django 5.0.6 on 2024-05-20 03:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0012_remove_checkin_checked_in_alter_checkin_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='check_out_time',
        ),
        migrations.AddField(
            model_name='checkin',
            name='checked_in',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2024, 5, 20, 3, 8, 6, 946814, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkin',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
