# Generated by Django 5.0.6 on 2024-05-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0014_inout_delete_checkin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inout',
            old_name='time',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='inout',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
