# Generated by Django 5.0.6 on 2024-05-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0015_rename_time_inout_start_time_inout_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inout',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
