# Generated by Django 5.0.6 on 2024-05-20 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0020_alter_inout_start_time'),
        ('mvp', '0021_set_default_start_time'),
    ]

    operations = [
    ]
