# Generated by Django 5.0.6 on 2024-05-21 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0022_merge_20240520_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinout',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
