# Generated by Django 5.0.6 on 2024-05-21 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0023_checkinout_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='inout',
            name='parking_fee',
            field=models.FloatField(default=0.0),
        ),
    ]
