# Generated by Django 5.0.6 on 2024-05-21 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0024_inout_parking_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinout',
            name='parking_fee',
            field=models.FloatField(default=0.0),
        ),
    ]
